CXX = g++
CXXFLAGS = -Wall

all: successful unsuccessful

successful: demo-successful.cpp
	$(CXX) $(CXXFLAGS) demo-successful.cpp -o successful

unsuccessful: demo-unsuccessful.cpp
	$(CXX) $(CXXFLAGS) demo-unsuccessful.cpp -o unsuccessful

